package com.wwbz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDivideWwbz<M extends BaseDivideWwbz<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setMoney(java.lang.Double money) {
		set("money", money);
	}

	public java.lang.Double getMoney() {
		return get("money");
	}

	public void setAllot(java.lang.String allot) {
		set("allot", allot);
	}

	public java.lang.String getAllot() {
		return get("allot");
	}

	public void setOut(java.lang.Double out) {
		set("out", out);
	}

	public java.lang.Double getOut() {
		return get("out");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}

	public java.lang.String getOpenid() {
		return get("openid");
	}

	public void setBank(java.lang.String bank) {
		set("bank", bank);
	}

	public java.lang.String getBank() {
		return get("bank");
	}

	public void setBranch(java.lang.String branch) {
		set("branch", branch);
	}

	public java.lang.String getBranch() {
		return get("branch");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public void setBankname(java.lang.String bankname) {
		set("bankname", bankname);
	}

	public java.lang.String getBankname() {
		return get("bankname");
	}

	public void setHeadmoney(java.lang.Double headmoney) {
		set("headmoney", headmoney);
	}

	public java.lang.Double getHeadmoney() {
		return get("headmoney");
	}

	public void setHeadout(java.lang.Double headout) {
		set("headout", headout);
	}

	public java.lang.Double getHeadout() {
		return get("headout");
	}

}
