package com.wwbz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBasicWwbz<M extends BaseBasicWwbz<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setReword(java.lang.String reword) {
		set("reword", reword);
	}

	public java.lang.String getReword() {
		return get("reword");
	}

	public void setAboutus(java.lang.String aboutus) {
		set("aboutus", aboutus);
	}

	public java.lang.String getAboutus() {
		return get("aboutus");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setPay(java.lang.String pay) {
		set("pay", pay);
	}

	public java.lang.String getPay() {
		return get("pay");
	}

	public void setPosterurl(java.lang.String posterurl) {
		set("posterurl", posterurl);
	}

	public java.lang.String getPosterurl() {
		return get("posterurl");
	}

	public void setPosterword(java.lang.String posterword) {
		set("posterword", posterword);
	}

	public java.lang.String getPosterword() {
		return get("posterword");
	}

	public void setDealerimg(java.lang.String dealerimg) {
		set("dealerimg", dealerimg);
	}

	public java.lang.String getDealerimg() {
		return get("dealerimg");
	}

	public void setDealerword(java.lang.String dealerword) {
		set("dealerword", dealerword);
	}

	public java.lang.String getDealerword() {
		return get("dealerword");
	}

}
