package com.wwbz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArchivesWwbz<M extends BaseArchivesWwbz<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}

	public java.lang.String getOpenid() {
		return get("openid");
	}

	public void setWxicon(java.lang.String wxicon) {
		set("wxicon", wxicon);
	}

	public java.lang.String getWxicon() {
		return get("wxicon");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setAge(java.lang.Integer age) {
		set("age", age);
	}

	public java.lang.Integer getAge() {
		return get("age");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public void setWeight(java.lang.String weight) {
		set("weight", weight);
	}

	public java.lang.String getWeight() {
		return get("weight");
	}

	public void setLow(java.lang.String low) {
		set("low", low);
	}

	public java.lang.String getLow() {
		return get("low");
	}

	public void setHigh(java.lang.String high) {
		set("high", high);
	}

	public java.lang.String getHigh() {
		return get("high");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setIllness(java.lang.String illness) {
		set("illness", illness);
	}

	public java.lang.String getIllness() {
		return get("illness");
	}

	public void setMedicine(java.lang.String medicine) {
		set("medicine", medicine);
	}

	public java.lang.String getMedicine() {
		return get("medicine");
	}

	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}

	public java.lang.String getPic() {
		return get("pic");
	}

	public void setShare(java.lang.Integer share) {
		set("share", share);
	}

	public java.lang.Integer getShare() {
		return get("share");
	}

	public void setStates(java.lang.Integer states) {
		set("states", states);
	}

	public java.lang.Integer getStates() {
		return get("states");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setFpg(java.lang.String fpg) {
		set("fpg", fpg);
	}

	public java.lang.String getFpg() {
		return get("fpg");
	}

	public void setVpg(java.lang.String vpg) {
		set("vpg", vpg);
	}

	public java.lang.String getVpg() {
		return get("vpg");
	}

	public void setHbaic(java.lang.String hbaic) {
		set("hbaic", hbaic);
	}

	public java.lang.String getHbaic() {
		return get("hbaic");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setOrder(java.lang.Integer order) {
		set("order", order);
	}

	public java.lang.Integer getOrder() {
		return get("order");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setHeight(java.lang.Integer height) {
		set("height", height);
	}

	public java.lang.Integer getHeight() {
		return get("height");
	}

	public void setNation(java.lang.String nation) {
		set("nation", nation);
	}

	public java.lang.String getNation() {
		return get("nation");
	}

	public void setDescribe(java.lang.String describe) {
		set("describe", describe);
	}

	public java.lang.String getDescribe() {
		return get("describe");
	}

	public void setNewill(java.lang.String newill) {
		set("newill", newill);
	}

	public java.lang.String getNewill() {
		return get("newill");
	}

}
