package com.wwbz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDealerWwbz<M extends BaseDealerWwbz<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}

	public java.lang.String getOpenid() {
		return get("openid");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setQrcode(java.lang.String qrcode) {
		set("qrcode", qrcode);
	}

	public java.lang.String getQrcode() {
		return get("qrcode");
	}

	public void setStates(java.lang.Integer states) {
		set("states", states);
	}

	public java.lang.Integer getStates() {
		return get("states");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setKind(java.lang.String kind) {
		set("kind", kind);
	}

	public java.lang.String getKind() {
		return get("kind");
	}

	public void setPolicy(java.lang.String policy) {
		set("policy", policy);
	}

	public java.lang.String getPolicy() {
		return get("policy");
	}

	public void setPay(java.lang.Integer pay) {
		set("pay", pay);
	}

	public java.lang.Integer getPay() {
		return get("pay");
	}

	public void setAnswer(java.lang.String answer) {
		set("answer", answer);
	}

	public java.lang.String getAnswer() {
		return get("answer");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setAge(java.lang.Integer age) {
		set("age", age);
	}

	public java.lang.Integer getAge() {
		return get("age");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setWechat(java.lang.String wechat) {
		set("wechat", wechat);
	}

	public java.lang.String getWechat() {
		return get("wechat");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setForecast(java.lang.Integer forecast) {
		set("forecast", forecast);
	}

	public java.lang.Integer getForecast() {
		return get("forecast");
	}

	public void setDes(java.lang.String des) {
		set("des", des);
	}

	public java.lang.String getDes() {
		return get("des");
	}

	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}

	public java.lang.String getPic() {
		return get("pic");
	}

	public void setStorename(java.lang.String storename) {
		set("storename", storename);
	}

	public java.lang.String getStorename() {
		return get("storename");
	}

	public void setStoreaddress(java.lang.String storeaddress) {
		set("storeaddress", storeaddress);
	}

	public java.lang.String getStoreaddress() {
		return get("storeaddress");
	}

	public void setLongitude(java.lang.String longitude) {
		set("longitude", longitude);
	}

	public java.lang.String getLongitude() {
		return get("longitude");
	}

	public void setLatitude(java.lang.String latitude) {
		set("latitude", latitude);
	}

	public java.lang.String getLatitude() {
		return get("latitude");
	}

	public void setIsshow(java.lang.Integer isshow) {
		set("isshow", isshow);
	}

	public java.lang.Integer getIsshow() {
		return get("isshow");
	}

	public void setTotal(java.lang.Double total) {
		set("total", total);
	}

	public java.lang.Double getTotal() {
		return get("total");
	}

	public void setUnliquidated(java.lang.Double unliquidated) {
		set("unliquidated", unliquidated);
	}

	public java.lang.Double getUnliquidated() {
		return get("unliquidated");
	}

	public void setBank(java.lang.String bank) {
		set("bank", bank);
	}

	public java.lang.String getBank() {
		return get("bank");
	}

	public void setBranch(java.lang.String branch) {
		set("branch", branch);
	}

	public java.lang.String getBranch() {
		return get("branch");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public void setBankname(java.lang.String bankname) {
		set("bankname", bankname);
	}

	public java.lang.String getBankname() {
		return get("bankname");
	}

	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

	public void setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
	}

	public java.lang.String getUnionid() {
		return get("unionid");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setLogo(java.lang.String logo) {
		set("logo", logo);
	}

	public java.lang.String getLogo() {
		return get("logo");
	}

	public void setStart(java.lang.String start) {
		set("start", start);
	}

	public java.lang.String getStart() {
		return get("start");
	}

	public void setEnd(java.lang.String end) {
		set("end", end);
	}

	public java.lang.String getEnd() {
		return get("end");
	}

	public void setStoretel(java.lang.String storetel) {
		set("storetel", storetel);
	}

	public java.lang.String getStoretel() {
		return get("storetel");
	}

	public void setHeadtotal(java.lang.Double headtotal) {
		set("headtotal", headtotal);
	}

	public java.lang.Double getHeadtotal() {
		return get("headtotal");
	}

	public void setHeadunliquidated(java.lang.Double headunliquidated) {
		set("headunliquidated", headunliquidated);
	}

	public java.lang.Double getHeadunliquidated() {
		return get("headunliquidated");
	}

	public void setIshospital(java.lang.Integer ishospital) {
		set("ishospital", ishospital);
	}

	public java.lang.Integer getIshospital() {
		return get("ishospital");
	}

	public void setIshead(java.lang.Integer ishead) {
		set("ishead", ishead);
	}

	public java.lang.Integer getIshead() {
		return get("ishead");
	}

	public void setHeadpercent(java.lang.Double headpercent) {
		set("headpercent", headpercent);
	}

	public java.lang.Double getHeadpercent() {
		return get("headpercent");
	}

	public void setIsapply(java.lang.Integer isapply) {
		set("isapply", isapply);
	}

	public java.lang.Integer getIsapply() {
		return get("isapply");
	}

	public void setProclaim(java.lang.String proclaim) {
		set("proclaim", proclaim);
	}

	public java.lang.String getProclaim() {
		return get("proclaim");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

}
