package com.wwbz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBargaingoodsWwbz<M extends BaseBargaingoodsWwbz<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setEndtime(java.util.Date endtime) {
		set("endtime", endtime);
	}

	public java.util.Date getEndtime() {
		return get("endtime");
	}

	public void setGoodsid(java.lang.Integer goodsid) {
		set("goodsid", goodsid);
	}

	public java.lang.Integer getGoodsid() {
		return get("goodsid");
	}

	public void setStates(java.lang.Integer states) {
		set("states", states);
	}

	public java.lang.Integer getStates() {
		return get("states");
	}

	public void setPercent(java.lang.String percent) {
		set("percent", percent);
	}

	public java.lang.String getPercent() {
		return get("percent");
	}

	public void setHigh(java.lang.Integer high) {
		set("high", high);
	}

	public java.lang.Integer getHigh() {
		return get("high");
	}

	public void setLow(java.lang.Integer low) {
		set("low", low);
	}

	public java.lang.Integer getLow() {
		return get("low");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setWord(java.lang.String word) {
		set("word", word);
	}

	public java.lang.String getWord() {
		return get("word");
	}

	public void setOhigh(java.lang.Integer ohigh) {
		set("ohigh", ohigh);
	}

	public java.lang.Integer getOhigh() {
		return get("ohigh");
	}

	public void setOlow(java.lang.Integer olow) {
		set("olow", olow);
	}

	public java.lang.Integer getOlow() {
		return get("olow");
	}

	public void setSale(java.lang.Integer sale) {
		set("sale", sale);
	}

	public java.lang.Integer getSale() {
		return get("sale");
	}

}
