package com.wwbz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAllotWwbz<M extends BaseAllotWwbz<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setStart(int start) {
		set("start", start);
	}

	public java.lang.Long getStart() {
		return get("start");
	}

	public void setEnd(int end) {
		set("end", end);
	}

	public java.lang.Long getEnd() {
		return get("end");
	}

	public void setPercent(java.lang.Integer percent) {
		set("percent", percent);
	}

	public java.lang.Integer getPercent() {
		return get("percent");
	}

	public void setStates(java.lang.Integer states) {
		set("states", states);
	}

	public java.lang.Integer getStates() {
		return get("states");
	}

}
