package com.wwbz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBasicWwbzgl<M extends BaseBasicWwbzgl<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setProtocol(java.lang.String protocol) {
		set("protocol", protocol);
	}

	public java.lang.String getProtocol() {
		return get("protocol");
	}

	public void setDrrb(java.lang.String drrb) {
		set("drrb", drrb);
	}

	public java.lang.String getDrrb() {
		return get("drrb");
	}

	public void setDrzb(java.lang.String drzb) {
		set("drzb", drzb);
	}

	public java.lang.String getDrzb() {
		return get("drzb");
	}

	public void setDryb(java.lang.String dryb) {
		set("dryb", dryb);
	}

	public java.lang.String getDryb() {
		return get("dryb");
	}

	public void setDrnb(java.lang.String drnb) {
		set("drnb", drnb);
	}

	public java.lang.String getDrnb() {
		return get("drnb");
	}

	public void setDqrb(java.lang.String dqrb) {
		set("dqrb", dqrb);
	}

	public java.lang.String getDqrb() {
		return get("dqrb");
	}

	public void setDqzb(java.lang.String dqzb) {
		set("dqzb", dqzb);
	}

	public java.lang.String getDqzb() {
		return get("dqzb");
	}

	public void setDqyb(java.lang.String dqyb) {
		set("dqyb", dqyb);
	}

	public java.lang.String getDqyb() {
		return get("dqyb");
	}

	public void setDqnb(java.lang.String dqnb) {
		set("dqnb", dqnb);
	}

	public java.lang.String getDqnb() {
		return get("dqnb");
	}

}
