package com.wwbz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderWwbz<M extends BaseOrderWwbz<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMoney(java.lang.String money) {
		set("money", money);
	}

	public java.lang.String getMoney() {
		return get("money");
	}

	public void setOffset(java.lang.Integer offset) {
		set("offset", offset);
	}

	public java.lang.Integer getOffset() {
		return get("offset");
	}

	public void setBuytime(java.util.Date buytime) {
		set("buytime", buytime);
	}

	public java.util.Date getBuytime() {
		return get("buytime");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}

	public java.lang.String getOpenid() {
		return get("openid");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setOutTradeNo(java.lang.String outTradeNo) {
		set("out_trade_no", outTradeNo);
	}

	public java.lang.String getOutTradeNo() {
		return get("out_trade_no");
	}

	public void setGoodsid(java.lang.Integer goodsid) {
		set("goodsid", goodsid);
	}

	public java.lang.Integer getGoodsid() {
		return get("goodsid");
	}

	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

	public void setSheng(java.lang.String sheng) {
		set("sheng", sheng);
	}

	public java.lang.String getSheng() {
		return get("sheng");
	}

	public void setShi(java.lang.String shi) {
		set("shi", shi);
	}

	public java.lang.String getShi() {
		return get("shi");
	}

	public void setQu(java.lang.String qu) {
		set("qu", qu);
	}

	public java.lang.String getQu() {
		return get("qu");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setKind(java.lang.Integer kind) {
		set("kind", kind);
	}

	public java.lang.Integer getKind() {
		return get("kind");
	}

	public void setDirection(int i) {
		set("direction", i);
	}

	public java.lang.Long getDirection() {
		return get("direction");
	}

	public void setLw(java.lang.String lw) {
		set("lw", lw);
	}

	public java.lang.String getLw() {
		return get("lw");
	}

	public void setCom(java.lang.String com) {
		set("com", com);
	}

	public java.lang.String getCom() {
		return get("com");
	}

	public void setNum(java.lang.String num) {
		set("num", num);
	}

	public java.lang.String getNum() {
		return get("num");
	}

	public void setExpress(java.lang.String express) {
		set("express", express);
	}

	public java.lang.String getExpress() {
		return get("express");
	}

	public void setFatheropenid(java.lang.String fatheropenid) {
		set("fatheropenid", fatheropenid);
	}

	public java.lang.String getFatheropenid() {
		return get("fatheropenid");
	}

	public void setGoodsname(java.lang.String goodsname) {
		set("goodsname", goodsname);
	}

	public java.lang.String getGoodsname() {
		return get("goodsname");
	}

	public void setIscomment(java.lang.Integer iscomment) {
		set("iscomment", iscomment);
	}

	public java.lang.Integer getIscomment() {
		return get("iscomment");
	}

	public void setHeadopenid(java.lang.String headopenid) {
		set("headopenid", headopenid);
	}

	public java.lang.String getHeadopenid() {
		return get("headopenid");
	}

	public void setHeadpercent(java.lang.Double headpercent) {
		set("headpercent", headpercent);
	}

	public java.lang.Double getHeadpercent() {
		return get("headpercent");
	}

}
