package com.wwbz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCooperateWwbz<M extends BaseCooperateWwbz<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setStates(java.lang.Integer states) {
		set("states", states);
	}

	public java.lang.Integer getStates() {
		return get("states");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setMoney(java.lang.Integer money) {
		set("money", money);
	}

	public java.lang.Integer getMoney() {
		return get("money");
	}

	public void setDes(java.lang.String des) {
		set("des", des);
	}

	public java.lang.String getDes() {
		return get("des");
	}

	public void setIspay(java.lang.Integer ispay) {
		set("ispay", ispay);
	}

	public java.lang.Integer getIspay() {
		return get("ispay");
	}

	public void setIshospital(java.lang.Integer ishospital) {
		set("ishospital", ishospital);
	}

	public java.lang.Integer getIshospital() {
		return get("ishospital");
	}

	public void setIshead(java.lang.Integer ishead) {
		set("ishead", ishead);
	}

	public java.lang.Integer getIshead() {
		return get("ishead");
	}

	public void setPercent(java.lang.Double percent) {
		set("percent", percent);
	}

	public java.lang.Double getPercent() {
		return get("percent");
	}

}
