package com.wwbz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFeedWwbz<M extends BaseFeedWwbz<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setVpg(java.lang.String vpg) {
		set("vpg", vpg);
	}

	public java.lang.String getVpg() {
		return get("vpg");
	}

	public void setFpg(java.lang.String fpg) {
		set("fpg", fpg);
	}

	public java.lang.String getFpg() {
		return get("fpg");
	}

	public void setHbaic(java.lang.String hbaic) {
		set("hbaic", hbaic);
	}

	public java.lang.String getHbaic() {
		return get("hbaic");
	}

	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}

	public java.lang.String getPic() {
		return get("pic");
	}

	public void setDes(java.lang.String des) {
		set("des", des);
	}

	public java.lang.String getDes() {
		return get("des");
	}

	public void setStates(java.lang.Integer states) {
		set("states", states);
	}

	public java.lang.Integer getStates() {
		return get("states");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}

	public java.lang.String getOpenid() {
		return get("openid");
	}

	public void setLow(java.lang.String low) {
		set("low", low);
	}

	public java.lang.String getLow() {
		return get("low");
	}

	public void setHigh(java.lang.String high) {
		set("high", high);
	}

	public java.lang.String getHigh() {
		return get("high");
	}

	public void setStart(java.lang.String start) {
		set("start", start);
	}

	public java.lang.String getStart() {
		return get("start");
	}

	public void setEnd(java.lang.String end) {
		set("end", end);
	}

	public java.lang.String getEnd() {
		return get("end");
	}

}
