package com.wwbz.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("address_wwbz", "id", AddressWwbz.class);
		arp.addMapping("allot_wwbz", "id", AllotWwbz.class);
		arp.addMapping("archives_wwbz", "id", ArchivesWwbz.class);
		arp.addMapping("article_wwbz", "id", ArticleWwbz.class);
		arp.addMapping("article_wwbzgl", "id", ArticleWwbzgl.class);
		arp.addMapping("articlekind_wwbz", "id", ArticlekindWwbz.class);
		arp.addMapping("banner_wwbz", "id", BannerWwbz.class);
		arp.addMapping("banner_wwbzgl", "id", BannerWwbzgl.class);
		arp.addMapping("bargaingoods_wwbz", "id", BargaingoodsWwbz.class);
		arp.addMapping("bargainorder_wwbz", "id", BargainorderWwbz.class);
		arp.addMapping("basic_wwbz", "id", BasicWwbz.class);
		arp.addMapping("basic_wwbzgl", "id", BasicWwbzgl.class);
		arp.addMapping("cart_wwbz", "id", CartWwbz.class);
		arp.addMapping("category_wwbz", "id", CategoryWwbz.class);
		arp.addMapping("comment_wwbz", "id", CommentWwbz.class);
		arp.addMapping("cooperate_wwbz", "id", CooperateWwbz.class);
		arp.addMapping("customer_wwbz", "id", CustomerWwbz.class);
		arp.addMapping("dealer_wwbz", "id", DealerWwbz.class);
		arp.addMapping("divide_wwbz", "id", DivideWwbz.class);
		arp.addMapping("donate_wwbz", "id", DonateWwbz.class);
		arp.addMapping("feed_wwbz", "id", FeedWwbz.class);
		arp.addMapping("glucometer_wwbz", "id", GlucometerWwbz.class);
		arp.addMapping("goods_wwbz", "id", GoodsWwbz.class);
		arp.addMapping("invitation_wwbz", "id", InvitationWwbz.class);
		arp.addMapping("money_wwbz", "id", MoneyWwbz.class);
		arp.addMapping("offer_wwbz", "id", OfferWwbz.class);
		arp.addMapping("order_wwbz", "id", OrderWwbz.class);
		arp.addMapping("questionnaire_wwbz", "id", QuestionnaireWwbz.class);
		arp.addMapping("reward_wwbz", "id", RewardWwbz.class);
		arp.addMapping("rewardcontact_wwbz", "id", RewardcontactWwbz.class);
		arp.addMapping("store_wwbz", "id", StoreWwbz.class);
		arp.addMapping("transaction_wwbz", "id", TransactionWwbz.class);
		arp.addMapping("user_wwbz", "id", UserWwbz.class);
	}
}

