package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseAddressWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AddressWwbz extends BaseAddressWwbz<AddressWwbz> {
	public static final AddressWwbz dao = new AddressWwbz().dao();
}
