package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseAllotWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AllotWwbz extends BaseAllotWwbz<AllotWwbz> {
	public static final AllotWwbz dao = new AllotWwbz().dao();
}
