package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseArchivesWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArchivesWwbz extends BaseArchivesWwbz<ArchivesWwbz> {
	public static final ArchivesWwbz dao = new ArchivesWwbz().dao();
}
