package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseArticlekindWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticlekindWwbz extends BaseArticlekindWwbz<ArticlekindWwbz> {
	public static final ArticlekindWwbz dao = new ArticlekindWwbz().dao();
}
