package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseArticleWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleWwbz extends BaseArticleWwbz<ArticleWwbz> {
	public static final ArticleWwbz dao = new ArticleWwbz().dao();
}
