package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseArticleWwbzgl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleWwbzgl extends BaseArticleWwbzgl<ArticleWwbzgl> {
	public static final ArticleWwbzgl dao = new ArticleWwbzgl().dao();
}
