package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseBannerWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BannerWwbz extends BaseBannerWwbz<BannerWwbz> {
	public static final BannerWwbz dao = new BannerWwbz().dao();
}
