package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseBannerWwbzgl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BannerWwbzgl extends BaseBannerWwbzgl<BannerWwbzgl> {
	public static final BannerWwbzgl dao = new BannerWwbzgl().dao();
}
