package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseBargaingoodsWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BargaingoodsWwbz extends BaseBargaingoodsWwbz<BargaingoodsWwbz> {
	public static final BargaingoodsWwbz dao = new BargaingoodsWwbz().dao();
}
