package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseBargainorderWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BargainorderWwbz extends BaseBargainorderWwbz<BargainorderWwbz> {
	public static final BargainorderWwbz dao = new BargainorderWwbz().dao();
}
