package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseBasicWwbzgl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicWwbzgl extends BaseBasicWwbzgl<BasicWwbzgl> {
	public static final BasicWwbzgl dao = new BasicWwbzgl().dao();
}
