package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseBasicWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicWwbz extends BaseBasicWwbz<BasicWwbz> {
	public static final BasicWwbz dao = new BasicWwbz().dao();
}
