package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseCartWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CartWwbz extends BaseCartWwbz<CartWwbz> {
	public static final CartWwbz dao = new CartWwbz().dao();
}
