package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseCategoryWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CategoryWwbz extends BaseCategoryWwbz<CategoryWwbz> {
	public static final CategoryWwbz dao = new CategoryWwbz().dao();
}
