package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseCommentWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentWwbz extends BaseCommentWwbz<CommentWwbz> {
	public static final CommentWwbz dao = new CommentWwbz().dao();
}
