package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseCooperateWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CooperateWwbz extends BaseCooperateWwbz<CooperateWwbz> {
	public static final CooperateWwbz dao = new CooperateWwbz().dao();
}
