package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseCustomerWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerWwbz extends BaseCustomerWwbz<CustomerWwbz> {
	public static final CustomerWwbz dao = new CustomerWwbz().dao();
}
