package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseDealerWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DealerWwbz extends BaseDealerWwbz<DealerWwbz> {
	public static final DealerWwbz dao = new DealerWwbz().dao();
}
