package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseDiabetesWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DiabetesWwbz extends BaseDiabetesWwbz<DiabetesWwbz> {
	public static final DiabetesWwbz dao = new DiabetesWwbz().dao();
}
