package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseDivideWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DivideWwbz extends BaseDivideWwbz<DivideWwbz> {
	public static final DivideWwbz dao = new DivideWwbz().dao();
}
