package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseDonateWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DonateWwbz extends BaseDonateWwbz<DonateWwbz> {
	public static final DonateWwbz dao = new DonateWwbz().dao();
}
