package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseFeedWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FeedWwbz extends BaseFeedWwbz<FeedWwbz> {
	public static final FeedWwbz dao = new FeedWwbz().dao();
}
