package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseGlucometerWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GlucometerWwbz extends BaseGlucometerWwbz<GlucometerWwbz> {
	public static final GlucometerWwbz dao = new GlucometerWwbz().dao();
}
