package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseGoodsWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsWwbz extends BaseGoodsWwbz<GoodsWwbz> {
	public static final GoodsWwbz dao = new GoodsWwbz().dao();
}
