package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseInvitationWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InvitationWwbz extends BaseInvitationWwbz<InvitationWwbz> {
	public static final InvitationWwbz dao = new InvitationWwbz().dao();
}
