package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseMoneyWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MoneyWwbz extends BaseMoneyWwbz<MoneyWwbz> {
	public static final MoneyWwbz dao = new MoneyWwbz().dao();
}
