package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseOfferWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OfferWwbz extends BaseOfferWwbz<OfferWwbz> {
	public static final OfferWwbz dao = new OfferWwbz().dao();
}
