package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseOrderWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderWwbz extends BaseOrderWwbz<OrderWwbz> {
	public static final OrderWwbz dao = new OrderWwbz().dao();
}
