package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseQuestionnaireWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionnaireWwbz extends BaseQuestionnaireWwbz<QuestionnaireWwbz> {
	public static final QuestionnaireWwbz dao = new QuestionnaireWwbz().dao();
}
