package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseRewardcontactWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RewardcontactWwbz extends BaseRewardcontactWwbz<RewardcontactWwbz> {
	public static final RewardcontactWwbz dao = new RewardcontactWwbz().dao();
}
