package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseRewardWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RewardWwbz extends BaseRewardWwbz<RewardWwbz> {
	public static final RewardWwbz dao = new RewardWwbz().dao();
}
