package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseStoreWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreWwbz extends BaseStoreWwbz<StoreWwbz> {
	public static final StoreWwbz dao = new StoreWwbz().dao();
}
