package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseTransactionWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TransactionWwbz extends BaseTransactionWwbz<TransactionWwbz> {
	public static final TransactionWwbz dao = new TransactionWwbz().dao();
}
