package com.wwbz.common.model;

import com.wwbz.common.model.base.BaseUserWwbz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserWwbz extends BaseUserWwbz<UserWwbz> {
	public static final UserWwbz dao = new UserWwbz().dao();
}
